import type { Component } from "vue";
import {
  Activity,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  Camera,
  CalendarDays,
  Check,
  ChevronDown,
  CircleHelp,
  Command,
  Copy,
  Delete,
  Download,
  Edit3,
  Eye,
  FileText,
  FolderTree,
  Gauge,
  Globe2,
  KeyRound,
  Languages,
  LayoutDashboard,
  ListFilter,
  LockKeyhole,
  LoaderCircle,
  LogOut,
  Maximize2,
  Mars,
  Menu,
  MessageSquareText,
  Minimize2,
  Moon,
  MoreHorizontal,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  Plus,
  RefreshCw,
  ScanLine,
  Search,
  Settings2,
  ShieldCheck,
  SlidersHorizontal,
  Sun,
  Trash2,
  Upload,
  UserRound,
  UsersRound,
  Video,
  Venus,
  X,
  ZoomIn,
} from "lucide-vue-next";

const iconMap: Record<string, Component> = {
  activity: Activity,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  bell: Bell,
  camera: Camera,
  "calendar-days": CalendarDays,
  calendar: CalendarDays,
  captcha: ScanLine,
  check: Check,
  "chevron-down": ChevronDown,
  close: X,
  close_all: X,
  close_left: ArrowLeft,
  close_other: X,
  close_right: ArrowRight,
  command: Command,
  copy: Copy,
  "circle-help": CircleHelp,
  delete: Delete,
  dashboard: LayoutDashboard,
  document: FileText,
  download: Download,
  edit: Pencil,
  edit3: Edit3,
  eye: Eye,
  folder: FolderTree,
  gauge: Gauge,
  globe: Globe2,
  homepage: LayoutDashboard,
  key: KeyRound,
  languages: Languages,
  "layout-dashboard": LayoutDashboard,
  list: Menu,
  "list-filter": ListFilter,
  "loader-circle": LoaderCircle,
  lock: LockKeyhole,
  logout: LogOut,
  maximize: Maximize2,
  menu: Menu,
  mars: Mars,
  message: MessageSquareText,
  minimize: Minimize2,
  moon: Moon,
  more: MoreHorizontal,
  "panel-left-close": PanelLeftClose,
  "panel-left-open": PanelLeftOpen,
  plus: Plus,
  position: Activity,
  refresh: RefreshCw,
  search: Search,
  settings: Settings2,
  shield: ShieldCheck,
  "shield-check": ShieldCheck,
  "sliders-horizontal": SlidersHorizontal,
  sun: Sun,
  trash: Trash2,
  upload: Upload,
  user: UserRound,
  "user-round": UserRound,
  users: UsersRound,
  "users-round": UsersRound,
  venus: Venus,
  video: Video,
  x: X,
  "zoom-in": ZoomIn,
};

export function resolveAppIcon(name: string): Component {
  const normalizedName = name.trim().toLowerCase();
  return iconMap[normalizedName] ?? CircleHelp;
}
