import type { Component } from "vue";
import {
  Activity,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Bell,
  BellRing,
  BookOpen,
  CalendarDays,
  Camera,
  Check,
  ChevronDown,
  CircleHelp,
  Command,
  Copy,
  Delete,
  Download,
  Edit3,
  Eye,
  FileText,
  FolderTree,
  Gauge,
  Globe2,
  KeyRound,
  Languages,
  LayoutDashboard,
  Link,
  ListFilter,
  LoaderCircle,
  LockKeyhole,
  LogOut,
  Mars,
  Maximize2,
  Megaphone,
  Menu,
  MessageSquareText,
  Minimize2,
  Moon,
  MoreHorizontal,
  Network,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  PlugZap,
  Plus,
  RefreshCw,
  ScanLine,
  ScrollText,
  Search,
  Settings2,
  ShieldCheck,
  ShieldUser,
  SlidersHorizontal,
  Sun,
  Trash2,
  Upload,
  UserRound,
  UsersRound,
  Venus,
  Video,
  X,
  ZoomIn,
} from "lucide-vue-next";

const iconMap: Record<string, Component> = {
  activity: Activity,
  api: PlugZap,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-up-right": ArrowUpRight,
  bell: Bell,
  calendar: CalendarDays,
  "calendar-days": CalendarDays,
  camera: Camera,
  captcha: ScanLine,
  check: Check,
  "chevron-down": ChevronDown,
  "circle-help": CircleHelp,
  close: X,
  close_all: X,
  close_left: ArrowLeft,
  close_other: X,
  close_right: ArrowRight,
  command: Command,
  copy: Copy,
  dashboard: LayoutDashboard,
  delete: Delete,
  dict: BookOpen,
  document: FileText,
  download: Download,
  edit: Pencil,
  edit3: Edit3,
  eye: Eye,
  "file-text": FileText,
  folder: FolderTree,
  gauge: Gauge,
  globe: Globe2,
  homepage: LayoutDashboard,
  key: KeyRound,
  languages: Languages,
  "layout-dashboard": LayoutDashboard,
  link: Link,
  list: Menu,
  "list-filter": ListFilter,
  "loader-circle": LoaderCircle,
  lock: LockKeyhole,
  log: ScrollText,
  logout: LogOut,
  mars: Mars,
  maximize: Maximize2,
  menu: Menu,
  message: MessageSquareText,
  minimize: Minimize2,
  moon: Moon,
  more: MoreHorizontal,
  notice: Megaphone,
  notification: BellRing,
  "panel-left-close": PanelLeftClose,
  "panel-left-open": PanelLeftOpen,
  pencil: Pencil,
  plus: Plus,
  position: Activity,
  refresh: RefreshCw,
  role: ShieldUser,
  search: Search,
  settings: Settings2,
  shield: ShieldCheck,
  "shield-check": ShieldCheck,
  "sliders-horizontal": SlidersHorizontal,
  sun: Sun,
  system: Settings2,
  trash: Trash2,
  tree: Network,
  upload: Upload,
  user: UserRound,
  "user-round": UserRound,
  users: UsersRound,
  "users-round": UsersRound,
  venus: Venus,
  video: Video,
  x: X,
  "zoom-in": ZoomIn,
};

/**
 * 后端菜单图标名的规范化：兼容 IconSelect 写入的 el-icon-Xxx 和 i-svg:xxx 前缀
 */
export function normalizeMenuIconName(value?: string | null, fallback = "menu") {
  return (value || fallback).replace(/^el-icon-/, "").replace(/^i-svg:/, "");
}

/** 名称是否有专属图标（没有时 resolveAppIcon 会回落到问号） */
export function hasAppIcon(name: string) {
  return name.trim().toLowerCase() in iconMap;
}

export function resolveAppIcon(name: string): Component {
  const normalizedName = name.trim().toLowerCase();
  return iconMap[normalizedName] ?? CircleHelp;
}
