import type { Component } from "vue";
import {
  Activity,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Blocks,
  Bell,
  BookOpen,
  Camera,
  CalendarDays,
  Check,
  ChevronDown,
  CircleHelp,
  Code2,
  Command,
  Copy,
  Download,
  Edit3,
  ExternalLink,
  Eye,
  FileText,
  FolderTree,
  GitBranch,
  Gauge,
  Globe2,
  KeyRound,
  Languages,
  LayoutDashboard,
  ListFilter,
  LockKeyhole,
  LoaderCircle,
  LogOut,
  Maximize2,
  Mars,
  Menu,
  MessageSquareText,
  Minimize2,
  Moon,
  MoreHorizontal,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  Plus,
  RefreshCw,
  ScanLine,
  Search,
  Settings2,
  ShieldCheck,
  SlidersHorizontal,
  Star,
  Sun,
  Trash2,
  Upload,
  UserRound,
  UsersRound,
  Video,
  Venus,
  WandSparkles,
  X,
  ZoomIn,
} from "@lucide/vue";

const iconMap: Record<string, Component> = {
  activity: Activity,
  api: Code2,
  backtop: ArrowUp,
  "arrow-down": ChevronDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  bell: Bell,
  bilibili: Video,
  blocks: Blocks,
  "book-open": BookOpen,
  browser: Globe2,
  camera: Camera,
  "calendar-days": CalendarDays,
  calendar: CalendarDays,
  captcha: ScanLine,
  client: Globe2,
  check: Check,
  "circle-close": X,
  "circle-close-filled": X,
  "chevron-down": ChevronDown,
  close: X,
  collapse: PanelLeftClose,
  "close-all": X,
  "close-left": ArrowLeft,
  "close-other": X,
  "close-right": ArrowRight,
  command: Command,
  cnblogs: Globe2,
  copy: Copy,
  "circle-help": CircleHelp,
  cascader: GitBranch,
  code: Code2,
  csdn: Globe2,
  delete: Trash2,
  dashboard: LayoutDashboard,
  dict: BookOpen,
  document: FileText,
  down: ChevronDown,
  download: Download,
  edit: Pencil,
  edit3: Edit3,
  "element-plus": Blocks,
  elementplus: Blocks,
  enter: ArrowRight,
  esc: X,
  eye: Eye,
  external: ExternalLink,
  file: FileText,
  "file-text": FileText,
  folder: FolderTree,
  fullscreen: Maximize2,
  "fullscreen-exit": Minimize2,
  gauge: Gauge,
  git: GitBranch,
  gitcode: GitBranch,
  gitee: GitBranch,
  github: GitBranch,
  globe: Globe2,
  homepage: LayoutDashboard,
  java: Code2,
  juejin: Globe2,
  key: KeyRound,
  languages: Languages,
  language: Languages,
  "layout-dashboard": LayoutDashboard,
  link: ExternalLink,
  list: Menu,
  "list-filter": ListFilter,
  "loader-circle": LoaderCircle,
  lock: LockKeyhole,
  log: FileText,
  logout: LogOut,
  magicstick: WandSparkles,
  "magic-stick": WandSparkles,
  maximize: Maximize2,
  menu: Menu,
  mars: Mars,
  message: MessageSquareText,
  monitor: Gauge,
  minimize: Minimize2,
  moon: Moon,
  more: MoreHorizontal,
  notification: Bell,
  notice: Bell,
  operation: ListFilter,
  "panel-left-close": PanelLeftClose,
  "panel-left-open": PanelLeftOpen,
  pencil: Pencil,
  plus: Plus,
  position: Activity,
  project: FolderTree,
  qq: MessageSquareText,
  "question-filled": CircleHelp,
  refresh: RefreshCw,
  "refresh-left": RefreshCw,
  "refresh-right": RefreshCw,
  role: ShieldCheck,
  search: Search,
  settings: Settings2,
  setting: Settings2,
  shield: ShieldCheck,
  "shield-check": ShieldCheck,
  "sliders-horizontal": SlidersHorizontal,
  size: SlidersHorizontal,
  sun: Sun,
  star: Star,
  "star-filled": Star,
  system: Settings2,
  table: Menu,
  todo: Check,
  trash: Trash2,
  tree: FolderTree,
  typescript: Code2,
  up: ArrowUp,
  upload: Upload,
  "upload-filled": Upload,
  user: UserRound,
  "user-round": UserRound,
  users: UsersRound,
  "users-round": UsersRound,
  "verify-code": ScanLine,
  venus: Venus,
  video: Video,
  visitor: UserRound,
  view: Eye,
  vue: Code2,
  wand: WandSparkles,
  wechat: MessageSquareText,
  x: X,
  xml: Code2,
  "zoom-in": ZoomIn,
  sunny: Sun,
};

export const APP_ICON_NAMES = [
  "activity",
  "api",
  "arrow-down",
  "arrow-left",
  "arrow-right",
  "arrow-up",
  "bell",
  "blocks",
  "book-open",
  "calendar-days",
  "captcha",
  "check",
  "circle-help",
  "close",
  "code",
  "copy",
  "dashboard",
  "delete",
  "dict",
  "document",
  "download",
  "edit",
  "external",
  "eye",
  "file-text",
  "folder",
  "gauge",
  "git",
  "github",
  "globe",
  "key",
  "languages",
  "link",
  "list-filter",
  "loader-circle",
  "lock",
  "magic-stick",
  "menu",
  "message",
  "minimize",
  "moon",
  "more",
  "panel-left-close",
  "panel-left-open",
  "pencil",
  "plus",
  "refresh",
  "role",
  "search",
  "settings",
  "shield-check",
  "sliders-horizontal",
  "star",
  "sun",
  "trash",
  "tree",
  "upload",
  "user-round",
  "users-round",
  "verify-code",
  "venus",
  "video",
  "wand",
  "x",
  "zoom-in",
] as const;

export function normalizeAppIconName(name: string): string {
  return name
    .trim()
    .replace(/^i-svg:/i, "")
    .replace(/^el-icon[-:]/i, "")
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/_/g, "-")
    .toLowerCase();
}

export function resolveAppIcon(name: string): Component {
  return iconMap[normalizeAppIconName(name)] ?? CircleHelp;
}
