# Generated by Django 4.2.24 on 2026-09-25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("system", "0008_operationlog_audit_context"),
    ]

    operations = [
        migrations.CreateModel(
            name="OidcIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("issuer", models.CharField(max_length=255, verbose_name="身份提供方")),
                ("subject", models.CharField(max_length=255, verbose_name="外部用户标识")),
                (
                    "email",
                    models.CharField(blank=True, default="", max_length=254, verbose_name="登录邮箱"),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最近登录时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oidc_identities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="本地用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "单点登录身份",
                "verbose_name_plural": "单点登录身份",
                "db_table": "oauth_oidc_identities",
                "unique_together": {("issuer", "subject")},
            },
        ),
    ]
