# Generated by Django 4.2.24 on 2025-09-29 05:45

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import drf_admin.apps.system.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dicts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dict_code', models.CharField(max_length=32, unique=True, verbose_name='字典编码')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='字典名称')),
                ('status', models.IntegerField(default=1, verbose_name='排序')),
                ('remark', models.CharField(blank=True, default='', max_length=50, verbose_name='备注')),
            ],
            options={
                'verbose_name': '字典',
                'verbose_name_plural': '字典',
                'db_table': 'system_dicts',
                'ordering': ['dict_code'],
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('type', models.CharField(blank=True, choices=[('CATALOG', '根目录'), ('MENU', '菜单'), ('BUTTON', '按钮'), ('EXTLINK', '外链')], default='', max_length=8, verbose_name='权限类型')),
                ('route_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='路由名')),
                ('route_path', models.CharField(blank=True, max_length=200, null=True, verbose_name='路由路径')),
                ('component', models.CharField(blank=True, max_length=200, null=True, verbose_name='组件路径')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('visible', models.IntegerField(default=1, verbose_name='是否可见')),
                ('icon', models.CharField(blank=True, max_length=30, null=True, verbose_name='图标')),
                ('redirect', models.CharField(blank=True, max_length=200, null=True, verbose_name='重定向')),
                ('perm', models.CharField(blank=True, max_length=200, null=True, verbose_name='权限标识')),
                ('keepAlive', models.BooleanField(blank=True, null=True, verbose_name='是否缓存')),
                ('alwaysShow', models.BooleanField(blank=True, null=True, verbose_name='是否一直显示')),
                ('params', models.JSONField(default=list, verbose_name='参数')),
                ('desc', models.CharField(blank=True, max_length=30, null=True, verbose_name='权限描述')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.permissions', verbose_name='父菜单')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'system_permissions',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='角色')),
                ('code', models.CharField(blank=True, max_length=32, null=True, verbose_name='角色编码')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_default', models.IntegerField(default=0, verbose_name='是否默认角色（新用户自动分配）')),
                ('desc', models.CharField(blank=True, default='', max_length=50, verbose_name='描述')),
                ('permissions', models.ManyToManyField(blank=True, db_table='system_roles_to_system_permissions', to='system.permissions', verbose_name='权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'system_roles',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='DictItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('label', models.CharField(max_length=32, verbose_name='字典项名称')),
                ('value', models.CharField(max_length=32, verbose_name='字典编码')),
                ('sort', models.IntegerField(default=1, verbose_name='排序')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('tag_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='标签类型')),
                ('dict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.dicts', verbose_name='字典')),
            ],
            options={
                'verbose_name': '字典项',
                'verbose_name_plural': '字典项',
                'db_table': 'system_dict_items',
                'ordering': ['dict', 'sort'],
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=32, verbose_name='部门')),
                ('status', models.IntegerField(default=1, verbose_name='状态')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.departments', verbose_name='父部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'system_departments',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, default='', max_length=20, verbose_name='真实姓名')),
                ('mobile', models.CharField(blank=True, default=None, max_length=11, null=True, unique=True, verbose_name='手机号码')),
                ('image', models.ImageField(blank=True, default='avatar/default.png', upload_to=drf_admin.apps.system.models.user_avatar_path, verbose_name='头像')),
                ('gender', models.IntegerField(choices=[(0, '保密'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('is_active', models.IntegerField(default=1, verbose_name='是否激活')),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.departments', verbose_name='直属部门')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('roles', models.ManyToManyField(blank=True, db_table='system_users_to_system_roles', to='system.roles', verbose_name='角色')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'system_users',
                'ordering': ['id'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
