# Generated by Django 4.2.24 on 2025-10-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictitems',
            options={'ordering': ['dict', 'value'], 'verbose_name': '字典项', 'verbose_name_plural': '字典项'},
        ),
        migrations.RemoveField(
            model_name='dictitems',
            name='sort',
        ),
        migrations.AlterField(
            model_name='dictitems',
            name='label',
            field=models.CharField(max_length=32, verbose_name='字典项标签'),
        ),
        migrations.AlterField(
            model_name='dictitems',
            name='value',
            field=models.CharField(max_length=32, verbose_name='字典项值'),
        ),
    ]
