# Generated by Django 4.2.24 on 2026-06-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_dictitems_options_remove_dictitems_sort_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('type', models.IntegerField(default=0, verbose_name='类型')),
                ('level', models.CharField(default='L', max_length=10, verbose_name='级别')),
                ('target_type', models.IntegerField(default=1, verbose_name='目标类型')),
                ('target_user_ids', models.JSONField(default=list, verbose_name='目标用户ID列表')),
                ('publisher_id', models.IntegerField(blank=True, null=True, verbose_name='发布人ID')),
                ('publisher_name', models.CharField(blank=True, default='', max_length=50, verbose_name='发布人名称')),
                ('publish_status', models.IntegerField(default=0, verbose_name='发布状态')),
                ('publish_time', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('revoke_time', models.DateTimeField(blank=True, null=True, verbose_name='撤回时间')),
            ],
            options={
                'verbose_name': '通知公告',
                'verbose_name_plural': '通知公告',
                'db_table': 'system_notices',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['publish_status'], name='system_noti_publish_679f9c_idx'), models.Index(fields=['publisher_id'], name='system_noti_publish_4efe6f_idx'), models.Index(fields=['publish_status', 'publish_time'], name='system_noti_publish_6b1619_idx')],
            },
        ),
    ]
