# Generated by Django 4.2.24 on 2026-06-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_notices'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户ID')),
                ('username', models.CharField(blank=True, default='', max_length=150, verbose_name='用户名')),
                ('name', models.CharField(blank=True, default='', max_length=50, verbose_name='用户姓名')),
                ('operation', models.CharField(blank=True, default='', max_length=100, verbose_name='操作描述')),
                ('method', models.CharField(blank=True, default='', max_length=10, verbose_name='请求方法')),
                ('path', models.CharField(blank=True, default='', max_length=500, verbose_name='请求路径')),
                ('query_params', models.TextField(blank=True, default='', verbose_name='查询参数')),
                ('request_body', models.TextField(blank=True, default='', verbose_name='请求体')),
                ('response_status', models.IntegerField(default=0, verbose_name='响应状态码')),
                ('response_body', models.TextField(blank=True, default='', verbose_name='响应体')),
                ('ip', models.CharField(blank=True, default='', max_length=50, verbose_name='IP地址')),
                ('browser', models.CharField(blank=True, default='', max_length=100, verbose_name='浏览器')),
                ('os', models.CharField(blank=True, default='', max_length=100, verbose_name='操作系统')),
                ('execution_time', models.IntegerField(default=0, verbose_name='执行时间(毫秒)')),
                ('status', models.IntegerField(default=1, verbose_name='状态(1:成功;0:失败)')),
                ('error_msg', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'system_operation_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='system_oper_user_id_655f12_idx'), models.Index(fields=['username'], name='system_oper_usernam_32bf19_idx'), models.Index(fields=['status'], name='system_oper_status_5c8690_idx'), models.Index(fields=['method'], name='system_oper_method_c4dd1d_idx'), models.Index(fields=['user_id', 'created_at'], name='system_oper_user_id_43aa98_idx'), models.Index(fields=['status', 'created_at'], name='system_oper_status_01dbe4_idx')],
            },
        ),
    ]
