# Generated by Django 4.2.24 on 2026-07-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_roles_data_scope_data_depts'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationlog',
            name='request_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='请求ID'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['request_id'], name='system_oper_request_b48508_idx'),
        ),
    ]
