# Generated by Django 4.2.24 on 2026-07-28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0006_operationlog_request_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoticeReads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("update_time", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("user_id", models.IntegerField(verbose_name="用户ID")),
                ("read_time", models.DateTimeField(auto_now_add=True, verbose_name="已读时间")),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reads",
                        to="system.notices",
                        verbose_name="通知",
                    ),
                ),
            ],
            options={
                "verbose_name": "通知已读记录",
                "verbose_name_plural": "通知已读记录",
                "db_table": "system_notice_reads",
                "indexes": [
                    models.Index(
                        fields=["user_id"],
                        name="system_noti_user_id_fbd5df_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("notice", "user_id"),
                        name="system_notice_reads_notice_user_uniq",
                    ),
                ],
            },
        ),
    ]
