# Generated by Django 4.2.24 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0007_noticereads"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationlog",
            name="object_type",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="业务对象类型",
            ),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="object_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="业务对象ID",
            ),
        ),
        migrations.AddField(
            model_name="operationlog",
            name="request_context",
            field=models.JSONField(
                blank=True,
                default=dict,
                verbose_name="结构化请求上下文",
            ),
        ),
        migrations.AddIndex(
            model_name="operationlog",
            index=models.Index(
                fields=["object_type", "object_id"],
                name="system_oper_object__audit_idx",
            ),
        ),
    ]
